/* Dirección: laboratorio editorial tecnológico. Esta página combina manifiesto, dossier de servicios y línea temporal académica. */
import { useState } from "react";
import { ArrowUpRight, Brain, Check, ChevronRight, Database, FileDown, Github, Globe2, Linkedin, Menu, Network, Search, ShieldCheck, Sparkles, X } from "lucide-react";

const socialLinks = { github: "https://github.com/profesor-ai-2030", linkedin: "https://www.linkedin.com/in/profesorbillpapas2030/", cv: "/manus-storage/curriculum-vitae-bill-papas_3711b2f5.pdf" };

const services = [
  { no: "01", icon: Globe2, title: "Diseño Web", text: "Experiencias digitales claras, rápidas y orientadas a objetivos, desde la arquitectura hasta la implementación.", tags: ["UX / UI", "React", "Estrategia"] },
  { no: "02", icon: Database, title: "Datos & Estadística", text: "Modelos de análisis empresarial que convierten información dispersa en patrones, métricas y decisiones.", tags: ["Big Data", "Dashboards", "Forecast"] },
  { no: "03", icon: Brain, title: "Inteligencia Artificial", text: "Aplicaciones prácticas de machine learning e IA para automatizar, descubrir y mejorar procesos.", tags: ["ML", "NLP", "Automatización"] },
  { no: "04", icon: Sparkles, title: "Brainstorming", text: "Sesiones estructuradas para ordenar ideas complejas, detectar oportunidades y diseñar próximos pasos.", tags: ["Ideación", "Talleres", "Innovación"] },
  { no: "05", icon: Search, title: "Google SEO", text: "Visibilidad orgánica con una estrategia técnica y editorial que hace encontrable el valor real de tu trabajo.", tags: ["Auditoría", "Contenido", "Crecimiento"] },
  { no: "06", icon: ShieldCheck, title: "Ciberseguridad", text: "Pensamiento preventivo para reconocer riesgos, proteger activos digitales y fortalecer la confianza.", tags: ["Riesgo", "Privacidad", "Buenas prácticas"] },
];

const studies = [
  { year: "1987", age: "18 años", title: "Inicio universitario", detail: "Comienza su formación superior en ciencias de la computación.", accent: "inicio" },
  { year: "1991", age: "22 años", title: "Bachiller en Ciencias de la Computación", detail: "Base sólida en programación, sistemas, algoritmos y pensamiento computacional.", accent: "degree" },
  { year: "1992", age: "23 años", title: "Master en Ciencia de Datos", detail: "Profundiza en estadística, modelado, análisis cuantitativo y toma de decisiones basada en datos.", accent: "degree" },
  { year: "1994", age: "25 años", title: "Investigación doctoral", detail: "Inicia una línea avanzada entre robótica científica, percepción y análisis cerebral robótico.", accent: "research" },
  { year: "1999", age: "30 años", title: "Doctorado completado", detail: "Culmina el Doctorado en Robótica Científica y Análisis Cerebral Robótico.", accent: "doctorate" },
];

const tech = ["Big Data", "Machine Learning", "Ciencia de Datos", "Ciberseguridad", "Robótica", "Python", "Análisis Estadístico", "Google SEO", "Sistemas Inteligentes", "Pensamiento Estratégico"];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [sent, setSent] = useState(false);

  const closeMenu = () => setMenuOpen(false);
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); closeMenu(); };

  return (
    <div className="min-h-screen bg-[#F7F3EA] text-[#203F48]">
      <header className="fixed top-0 z-50 w-full border-b border-[#203F48]/10 bg-[#F7F3EA]/90 backdrop-blur-xl">
        <div className="mx-auto flex max-w-[1280px] items-center justify-between px-5 py-4 lg:px-10">
          <a href="/" className="group flex items-center gap-3 text-left" aria-label="Ir a la página principal">
            <span className="relative grid h-10 w-10 place-items-center overflow-hidden rounded-full bg-[#203F48] shadow-lg shadow-[#203F48]/10"><img src="/assets/bill-papas-mark.webp" alt="Símbolo de Profesor Bill Papas" className="h-7 w-7 object-contain" /></span>
            <span className="hidden sm:block"><span className="block text-[.68rem] font-bold uppercase tracking-[.18em] text-[#C9794B]">Profesor</span><span className="block text-sm font-bold tracking-tight">Bill Papas</span></span>
          </a>
          <nav className="hidden items-center gap-8 lg:flex" aria-label="Navegación principal">
            {[['about','Perfil'],['services','Servicios'],['trajectory','Trayectoria'],['contact','Contacto']].map(([id,label]) => <button key={id} onClick={() => scrollTo(id)} className="text-xs font-bold uppercase tracking-[.14em] text-[#203F48]/65 transition-colors hover:text-[#C9794B]">{label}</button>)}
          </nav>
          <div className="hidden items-center gap-2 sm:flex"><a href={socialLinks.github} target="_blank" rel="noreferrer" aria-label="GitHub del Profesor Bill Papas" className="grid h-9 w-9 place-items-center border border-[#203F48]/15 text-[#203F48]/70 transition hover:border-[#C9794B] hover:text-[#C9794B]"><Github size={16} /></a><a href={socialLinks.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn del Profesor Bill Papas" className="grid h-9 w-9 place-items-center border border-[#203F48]/15 text-[#203F48]/70 transition hover:border-[#C9794B] hover:text-[#C9794B]"><Linkedin size={16} /></a><a href={socialLinks.cv} download="CV-Profesor-Bill-Papas.pdf" className="ml-2 flex items-center gap-2 border border-[#203F48] px-4 py-3 text-xs font-bold text-[#203F48] transition hover:-translate-y-0.5 hover:bg-[#203F48] hover:text-[#F7F3EA]"><FileDown size={15} /> CV</a><a href="https://wa.link/1g15fe" target="_blank" rel="noreferrer" aria-label="Conversar por WhatsApp" className="ml-1 flex items-center gap-2 rounded-full bg-[#203F48] px-5 py-3 text-xs font-bold text-[#F7F3EA] transition hover:-translate-y-0.5 hover:bg-[#C9794B]">Conversemos <ArrowUpRight size={15} /></a></div>
          <button className="rounded-full border border-[#203F48]/20 p-2 lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menú">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
        {menuOpen && <nav className="border-t border-[#203F48]/10 bg-[#F7F3EA] px-5 py-5 lg:hidden">{[['about','Perfil'],['services','Servicios'],['trajectory','Trayectoria'],['contact','Contacto']].map(([id,label]) => <button key={id} onClick={() => scrollTo(id)} className="block w-full border-b border-[#203F48]/10 py-3 text-left text-sm font-bold">{label}</button>)}<div className="flex items-center gap-3 pt-4"><a href={socialLinks.github} target="_blank" rel="noreferrer" aria-label="GitHub" className="flex items-center gap-2 border border-[#203F48]/15 px-3 py-2 text-xs font-bold"><Github size={15} /> GitHub</a><a href={socialLinks.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" className="flex items-center gap-2 border border-[#203F48]/15 px-3 py-2 text-xs font-bold"><Linkedin size={15} /> LinkedIn</a><a href={socialLinks.cv} download="CV-Profesor-Bill-Papas.pdf" className="flex items-center gap-2 border border-[#203F48] bg-[#203F48] px-3 py-2 text-xs font-bold text-[#F7F3EA]"><FileDown size={15} /> CV</a></div></nav>}
      </header>

      <main id="top">
        <section className="grain paper-grid relative overflow-hidden px-5 pb-20 pt-36 lg:px-10 lg:pb-28 lg:pt-48">
          <div className="mx-auto grid max-w-[1280px] items-center gap-14 lg:grid-cols-[.88fr_1.12fr] lg:gap-20">
            <div className="relative z-10 animate-reveal">
              <div className="mb-7 flex items-center gap-3"><span className="h-px w-12 bg-[#C9794B]" /><span className="section-label">Tecnología con criterio humano</span></div>
              <h1 className="max-w-2xl text-balance text-[clamp(2.75rem,7vw,6.9rem)] font-bold leading-[.94] tracking-[-.075em] text-[#203F48]">Pensar en<br /><span className="text-[#C9794B]">sistemas.</span><br />Construir futuro.</h1>
              <p className="mt-8 max-w-lg text-base leading-8 text-[#203F48]/70 lg:text-lg">Soy el Profesor Bill Papas. Acompaño a personas y organizaciones a convertir datos, inteligencia artificial y preguntas complejas en decisiones que se pueden ejecutar.</p>
              <div className="mt-10 flex flex-wrap items-center gap-4"><button onClick={() => scrollTo("services")} className="group flex items-center gap-3 rounded-full bg-[#C9794B] px-6 py-4 text-sm font-bold text-white shadow-xl shadow-[#C9794B]/15 transition hover:-translate-y-1">Explorar servicios <span className="grid h-6 w-6 place-items-center rounded-full bg-white/20 transition group-hover:rotate-45"><ArrowUpRight size={15} /></span></button><button onClick={() => scrollTo("trajectory")} className="flex items-center gap-2 px-3 py-3 text-sm font-bold text-[#203F48]">Ver trayectoria <ChevronRight size={16} className="text-[#C9794B]" /></button></div>
              <div className="mt-14 grid max-w-md grid-cols-3 gap-5 border-t border-[#203F48]/15 pt-5"><div><p className="text-2xl font-bold">30+</p><p className="mt-1 text-[.65rem] font-bold uppercase tracking-wider text-[#203F48]/50">Años de estudio</p></div><div><p className="text-2xl font-bold">05</p><p className="mt-1 text-[.65rem] font-bold uppercase tracking-wider text-[#203F48]/50">Áreas de servicio</p></div><div><p className="text-2xl font-bold">01</p><p className="mt-1 text-[.65rem] font-bold uppercase tracking-wider text-[#203F48]/50">Visión integral</p></div></div>
            </div>
            <div className="relative animate-reveal [animation-delay:180ms]">
              <div className="relative aspect-[1.06] overflow-hidden rounded-[2rem] bg-[#203F48] shadow-2xl shadow-[#203F48]/20"><img src="/assets/bill-papas-hero.webp" alt="Composición abstracta de robótica, datos e inteligencia artificial" className="h-full w-full object-cover opacity-90" /><div className="absolute inset-0 bg-gradient-to-tr from-[#203F48]/40 via-transparent to-[#C9794B]/10" /><div className="absolute bottom-5 left-5 flex items-center gap-3 rounded-full border border-white/20 bg-[#203F48]/75 px-4 py-2 text-[.65rem] font-bold uppercase tracking-[.18em] text-white backdrop-blur-md"><span className="h-2 w-2 rounded-full bg-[#C9794B]" /> Laboratorio de ideas aplicadas</div></div>
              <div className="absolute -bottom-7 -left-8 hidden h-28 w-28 rounded-full border border-[#C9794B]/50 bg-[#F7F3EA]/80 p-3 backdrop-blur-sm sm:block"><div className="orbit-spin h-full w-full rounded-full border border-dashed border-[#C9794B] p-3"><div className="grid h-full w-full place-items-center rounded-full bg-[#C9794B] text-center text-[.58rem] font-bold uppercase tracking-wider text-white">Datos<br />+<br />criterio</div></div></div>
              <div className="absolute -right-5 -top-6 hidden rounded-2xl border border-[#203F48]/10 bg-[#F7F3EA] p-4 shadow-xl sm:block"><p className="section-label mb-2">Nacido</p><p className="text-lg font-bold">28.03.1969</p><p className="mt-1 text-[.63rem] text-[#203F48]/50">Una mente en evolución constante</p></div>
            </div>
          </div>
        </section>

        <section id="about" className="border-y border-[#203F48]/10 bg-[#203F48] px-5 py-20 text-[#F7F3EA] lg:px-10 lg:py-28">
          <div className="mx-auto grid max-w-[1280px] gap-14 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><div><p className="section-label">/ 00 — Perfil</p><h2 className="mt-5 max-w-sm text-4xl font-bold leading-tight tracking-[-.05em] lg:text-5xl">La curiosidad también se puede diseñar.</h2></div><div className="max-w-2xl"><p className="text-xl leading-9 text-[#F7F3EA]/85">Con una formación que cruza computación, ciencia de datos y robótica, el Profesor Bill Papas trabaja en ese lugar donde la tecnología deja de ser una promesa y se convierte en una herramienta para entender mejor.</p><p className="mt-7 leading-8 text-[#F7F3EA]/55">Su enfoque combina investigación, conversación y prototipado. Antes de recomendar una solución, busca comprender el sistema completo: las personas, las restricciones, los datos y la oportunidad que aún no ha sido nombrada.</p><div className="mt-10 flex items-center gap-4"><img src="/assets/ai-robotics-technology.webp" alt="Logotipo AIRoboticsTechnology" className="h-16 w-16 rounded-full border border-[#F7F3EA]/20 bg-[#0B1029] object-cover" /><div><p className="font-bold">Profesor Bill Papas</p><p className="mt-1 text-xs text-[#F7F3EA]/50">Computación · Datos · Robótica · IA</p></div></div></div></div>
        </section>

        <section id="ai-robotics" className="border-b border-[#203F48]/10 bg-[#F7F3EA] px-5 py-16 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-[1280px] items-center gap-10 lg:grid-cols-[180px_1fr_auto] lg:gap-14"><div className="flex items-center gap-4 lg:block"><div className="grid h-24 w-24 place-items-center border border-[#203F48]/15 bg-[#0B1029] p-2"><img src="/assets/ai-robotics-technology.webp" alt="Logotipo AI Robotics Technology" className="h-full w-full object-contain" /></div><p className="mt-4 section-label">Marca / 01</p></div><div><h2 className="max-w-2xl text-3xl font-bold leading-tight tracking-[-.05em] lg:text-4xl">AI Robotics Technology: la expresión de una visión.</h2><p className="mt-5 max-w-2xl text-sm leading-8 text-[#203F48]/65">AI Robotics Technology es la marca con la que el Profesor Bill Papas reúne su experiencia en inteligencia artificial, robótica, ciencia de datos y sistemas inteligentes. Es un puente entre la investigación, la tecnología aplicada y las personas que buscan convertir ideas complejas en soluciones útiles.</p></div><div className="border-l-2 border-[#C9794B] pl-5 text-sm leading-7 text-[#203F48]/65"><p className="font-bold text-[#203F48]">Pensamiento humano.</p><p>Innovación responsable.</p><p>Robótica con propósito.</p></div></div></section>

        <section id="services" className="px-5 py-20 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1280px]"><div className="mb-14 grid gap-6 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="section-label">/ 01 — Servicios</p><h2 className="mt-5 max-w-md text-4xl font-bold leading-tight tracking-[-.06em] lg:text-6xl">Capacidades para avanzar.</h2></div><p className="max-w-xl text-base leading-8 text-[#203F48]/60">Cada servicio puede ser una conversación puntual o el comienzo de un acompañamiento más profundo. El punto de partida es siempre el mismo: una pregunta real.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map((service, i) => { const Icon = service.icon; return <article key={service.no} className="group relative overflow-hidden border border-[#203F48]/18 border-l-2 border-l-[#C9794B] bg-[#FCFAF4] p-7 transition duration-300 hover:-translate-y-1 hover:border-[#C9794B]/70 hover:shadow-xl hover:shadow-[#203F48]/5"><div className="flex items-start justify-between border-b border-[#203F48]/12 pb-4"><span className="text-xs font-bold tracking-[.2em] text-[#C9794B]">INDEX / {service.no}</span><Icon size={25} strokeWidth={1.5} className="text-[#203F48]/35 transition group-hover:text-[#C9794B]" /></div><h3 className="mt-10 text-xl font-bold">{service.title}</h3><p className="mt-4 min-h-[86px] text-sm leading-7 text-[#203F48]/60">{service.text}</p><div className="mt-7 flex flex-wrap gap-2">{service.tags.map(tag => <span key={tag} className="border border-[#203F48]/15 bg-transparent px-2.5 py-1.5 text-[.6rem] font-bold uppercase tracking-wider text-[#203F48]/60">{tag}</span>)}</div><div className="absolute -bottom-10 -right-10 h-28 w-28 rounded-full border border-[#C9794B]/15 transition group-hover:scale-125" /></article> })}</div></div></section>

        <section id="trajectory" className="paper-grid border-y border-[#203F48]/10 bg-[#EEE8DD] px-5 py-20 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1280px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="section-label">/ 02 — Trayectoria</p><h2 className="mt-5 max-w-md text-4xl font-bold leading-tight tracking-[-.06em] lg:text-6xl">Una línea de aprendizaje.</h2></div><div className="flex items-end justify-between gap-5"><p className="max-w-lg text-sm leading-7 text-[#203F48]/60">Calculada a partir de la fecha de nacimiento indicada: <strong className="text-[#203F48]">28 de marzo de 1969</strong>. El recorrido comienza a los 18 años.</p><span className="hidden text-7xl font-bold tracking-[-.08em] text-[#203F48]/10 lg:block">1969</span></div></div><div className="relative mt-16"><div className="absolute bottom-7 left-[22px] top-7 w-px bg-[#C9794B]/45 md:left-[112px]" />{studies.map((study, i) => <div key={study.year} className="group relative grid grid-cols-[45px_1fr] gap-5 pb-12 last:pb-0 md:grid-cols-[112px_1fr] md:gap-10"><div className="relative z-10 pt-1 text-xs font-bold text-[#C9794B] md:text-right md:text-sm">{study.year}</div><div className="relative border border-[#203F48]/15 bg-[#F7F3EA]/70 p-6 transition hover:border-[#C9794B]/60 hover:bg-[#F7F3EA] md:p-7"><span className="absolute -left-[30px] top-7 h-3 w-3 rounded-full border-2 border-[#EEE8DD] bg-[#C9794B] shadow-[0_0_0_4px_rgba(201,121,75,.18)] md:-left-[47px]" /><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-bold md:text-xl">{study.title}</h3><span className="rounded-full bg-[#203F48]/8 px-3 py-1 text-[.62rem] font-bold uppercase tracking-wider text-[#203F48]/55">{study.age}</span></div><p className="mt-3 max-w-2xl text-sm leading-7 text-[#203F48]/60">{study.detail}</p></div></div>)}</div></div></section>

        <section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-label">/ 03 — Campo de trabajo</p><h2 className="mt-5 max-w-md text-4xl font-bold leading-tight tracking-[-.06em] lg:text-5xl">Un mapa amplio para problemas complejos.</h2><p className="mt-6 max-w-md text-sm leading-7 text-[#203F48]/60">La especialidad no está en una sola herramienta. Está en saber cuándo combinar varias para encontrar una respuesta clara.</p></div><div className="flex flex-wrap content-start gap-3">{tech.map((item, i) => <span key={item} className={`rounded-full border px-5 py-3 text-sm font-bold transition hover:-translate-y-1 ${i % 3 === 0 ? 'border-[#C9794B]/50 bg-[#C9794B]/8 text-[#A75D37]' : 'border-[#203F48]/15 bg-[#FCFAF4] text-[#203F48]/75'}`}>{item}</span>)}</div></div></section>

        <section className="paper-grid border-y border-[#203F48]/10 bg-[#F7F3EA] px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="section-label">/ 04 — Método</p><h2 className="mt-5 max-w-3xl text-4xl font-bold leading-tight tracking-[-.06em] lg:text-6xl">La próxima buena idea empieza con una buena pregunta.</h2></div><div className="max-w-sm border-l-2 border-[#C9794B] pl-6 text-sm leading-7 text-[#203F48]/75"><p className="font-bold">01 · Escuchar</p><p className="mt-3 font-bold">02 · Mapear</p><p className="mt-3 font-bold">03 · Prototipar</p><p className="mt-3 font-bold">04 · Medir</p></div></div></section>

        <section id="contact" className="bg-[#203F48] px-5 py-20 text-[#F7F3EA] lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1280px] gap-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-24"><div><p className="section-label">/ 05 — Contacto</p><h2 className="mt-5 max-w-lg text-4xl font-bold leading-tight tracking-[-.06em] lg:text-6xl">Cuéntame qué estás intentando resolver.</h2><p className="mt-7 max-w-md text-base leading-8 text-[#F7F3EA]/55">No hace falta que tengas el problema perfectamente definido. Una conversación puede ser el primer mapa.</p><div className="mt-10 space-y-4 text-sm"><a href="mailto:profesor20262030@gmail.com" className="flex items-center gap-3 text-[#F7F3EA]/75 transition hover:text-[#C9794B]"><span className="grid h-9 w-9 place-items-center border border-[#F7F3EA]/15"><ArrowUpRight size={15} /></span> profesor20262030@gmail.com</a><div className="flex items-center gap-3 text-[#F7F3EA]/75"><span className="grid h-9 w-9 place-items-center rounded-full border border-[#F7F3EA]/15"><Network size={15} /></span> Consultoría remota y colaborativa</div></div></div><div className="border border-[#F7F3EA]/25 bg-[#F7F3EA] p-7 text-[#203F48] sm:p-9"><p className="section-label">Canal directo</p><h3 className="mt-5 text-2xl font-bold leading-tight">Hablemos por WhatsApp.</h3><p className="mt-4 text-sm leading-7 text-[#203F48]/65">Comparte tu reto, una idea o una pregunta. La conversación comienza directamente en WhatsApp, sin formularios intermedios.</p><a href="https://wa.link/e97smm" target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-3 border border-[#203F48] bg-[#203F48] px-6 py-4 text-sm font-bold text-[#F7F3EA] transition hover:-translate-y-0.5 hover:bg-[#C9794B]">Abrir WhatsApp <ArrowUpRight size={16} /></a><p className="mt-7 border-t border-[#203F48]/15 pt-5 text-xs text-[#203F48]/55">Correo de referencia: profesor20262030@gmail.com</p></div></div></section>
      </main>

      <footer className="border-t border-[#203F48]/10 bg-[#F7F3EA] px-5 py-8 lg:px-10"><div className="mx-auto flex max-w-[1280px] flex-col gap-4 text-[.68rem] font-bold uppercase tracking-[.13em] text-[#203F48]/50 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><img src="/assets/bill-papas-mark.webp" alt="Marca Bill Papas" className="h-7 w-7 rounded-full bg-[#203F48] p-1" /><span>Bill Papas / Archivo profesional</span></div><div className="leading-7 sm:text-right"><p>© 2026 | Creado por Profesor Bill Papas</p><p>© 2026 | Todos los Derechos Reservados</p></div></div></footer>
    </div>
  );
}
